"""composite unique constraint teller_account_id plus user_id

Revision ID: 80958ac94101
Revises: dd737a3548ab
Create Date: 2026-03-25 12:33:29.285978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80958ac94101'
down_revision: Union[str, Sequence[str], None] = 'dd737a3548ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('accounts_teller_account_id_key'), 'accounts', type_='unique')
    op.create_unique_constraint('uq_account_per_user', 'accounts', ['teller_account_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_per_user', 'accounts', type_='unique')
    op.create_unique_constraint(op.f('accounts_teller_account_id_key'), 'accounts', ['teller_account_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
