"""composite unique constraint teller_transaction_id plus account_id

Revision ID: 9732c2274d0c
Revises: 80958ac94101
Create Date: 2026-03-25 12:44:26.219677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9732c2274d0c'
down_revision: Union[str, Sequence[str], None] = '80958ac94101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_teller_transaction_id_key'), 'transactions', type_='unique')
    op.create_unique_constraint('uq_transaction_per_account', 'transactions', ['teller_transaction_id', 'account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_per_account', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('transactions_teller_transaction_id_key'), 'transactions', ['teller_transaction_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
